/**
 * 任务管理系统（localStorage版本）
 * Learning Tracker - Tasks Module
 */

class TaskManager {
  static TaskType = {
    DAILY_REQUIRED: 'daily_required',
    DAILY_OPTIONAL: 'daily_optional',
    WEEKLY_REQUIRED: 'weekly_required',
    WEEKLY_OPTIONAL: 'weekly_optional'
  };

  static TaskCategory = {
    STUDY: 'study',
    SPORTS: 'sports'
  };

  static createTask(data) {
    const user = Auth.getCurrentUser();
    if (!user) return null;

    const task = {
      id: Utils.generateId(),
      studentId: user.id,
      name: data.name,
      description: data.description || '',
      category: data.category || TaskManager.TaskCategory.STUDY,
      type: data.type,
      plannedDuration: data.plannedDuration || 30,
      pointsReward: data.pointsReward || 10,
      pointsPenalty: data.pointsPenalty || 5,
      createdAt: Date.now()
    };

    Storage.saveTemplate(task);
    return task;
  }

  static createFromTemplate(templateId, dateRange) {
    const templates = Storage.getTemplates();
    const template = templates.find(t => t.id === templateId);
    if (!template) return null;

    const user = Auth.getCurrentUser();
    if (!user) return null;

    const dates = Utils.getDateRange(dateRange.start, dateRange.end);
    const records = [];

    for (const date of dates) {
      const existingRecords = Storage.getRecords();
      const exists = existingRecords.some(r =>
        r.studentId === user.id &&
        r.templateId === templateId &&
        r.date === date
      );

      if (!exists) {
        const record = {
          id: Utils.generateId(),
          studentId: user.id,
          templateId: templateId,
          taskName: template.name,
          taskDescription: template.description,
          taskCategory: template.category,
          taskType: template.type,
          plannedDuration: template.plannedDuration,
          pointsReward: template.pointsReward,
          pointsPenalty: template.pointsPenalty,
          date: date,
          status: 'pending',
          actualDuration: null,
          startTime: null,
          endTime: null,
          ratings: null,
          summary: null,
          completedAt: null
        };

        Storage.saveRecord(record);
        records.push(record);
      }
    }

    return records;
  }

  static getDailyTasks(date = Utils.getToday()) {
    const user = Auth.getCurrentUser();
    if (!user) return { required: [], optional: [] };

    let records = Storage.getRecords();
    let todayRecords = records.filter(r =>
      r.studentId === user.id &&
      r.date === date &&
      (r.taskType === TaskManager.TaskType.DAILY_REQUIRED ||
       r.taskType === TaskManager.TaskType.DAILY_OPTIONAL)
    );

    if (todayRecords.length === 0 && date === Utils.getToday()) {
      const yesterday = new Date();
      yesterday.setDate(yesterday.getDate() - 1);
      const yesterdayStr = Utils.formatDate(yesterday);

      const yesterdayRecords = records.filter(r =>
        r.studentId === user.id &&
        r.date === yesterdayStr &&
        r.taskType === TaskManager.TaskType.DAILY_REQUIRED
      );

      if (yesterdayRecords.length > 0) {
        for (const yTask of yesterdayRecords) {
          const newRecord = {
            id: Utils.generateId(),
            studentId: user.id,
            templateId: yTask.templateId,
            taskName: yTask.taskName,
            taskDescription: yTask.taskDescription,
            taskCategory: yTask.taskCategory,
            taskType: TaskManager.TaskType.DAILY_REQUIRED,
            plannedDuration: yTask.plannedDuration,
            pointsReward: yTask.pointsReward,
            pointsPenalty: yTask.pointsPenalty,
            date: date,
            status: 'pending',
            actualDuration: null,
            startTime: null,
            endTime: null,
            ratings: null,
            summary: null,
            completedAt: null,
            autoGenerated: true
          };
          Storage.saveRecord(newRecord);
        }

        records = Storage.getRecords();
        todayRecords = records.filter(r =>
          r.studentId === user.id &&
          r.date === date &&
          (r.taskType === TaskManager.TaskType.DAILY_REQUIRED ||
           r.taskType === TaskManager.TaskType.DAILY_OPTIONAL)
        );
      }
    }

    return {
      required: todayRecords.filter(r => r.taskType === TaskManager.TaskType.DAILY_REQUIRED),
      optional: todayRecords.filter(r => r.taskType === TaskManager.TaskType.DAILY_OPTIONAL)
    };
  }

  static getWeeklyTasks() {
    const user = Auth.getCurrentUser();
    if (!user) return { required: [], optional: [] };

    const weekStart = Utils.getWeekStart();
    const weekDates = Utils.getWeekDates(weekStart);
    const today = Utils.getToday();

    let records = Storage.getRecords();

    const hasWeeklyTasks = records.some(r =>
      r.studentId === user.id &&
      r.taskType.startsWith('weekly') &&
      weekDates.includes(r.date)
    );

    if (!hasWeeklyTasks) {
      const lastWeekStart = new Date(weekStart);
      lastWeekStart.setDate(lastWeekStart.getDate() - 7);
      const lastWeekDates = Utils.getWeekDates(lastWeekStart);

      const lastWeekTasks = records.filter(r =>
        r.studentId === user.id &&
        lastWeekDates.includes(r.date) &&
        r.taskType.startsWith('weekly')
      );

      if (lastWeekTasks.length > 0) {
        for (const task of lastWeekTasks) {
          const existsInWeek = records.some(r =>
            r.studentId === user.id &&
            r.templateId === task.templateId &&
            weekDates.includes(r.date)
          );

          if (!existsInWeek) {
            const newRecord = {
              id: Utils.generateId(),
              studentId: user.id,
              templateId: task.templateId,
              taskName: task.taskName,
              taskDescription: task.taskDescription,
              taskCategory: task.taskCategory,
              taskType: task.taskType,
              plannedDuration: task.plannedDuration,
              pointsReward: task.pointsReward,
              pointsPenalty: task.pointsPenalty,
              date: weekDates[0],
              status: 'pending',
              actualDuration: null,
              startTime: null,
              endTime: null,
              ratings: null,
              summary: null,
              completedAt: null,
              autoGenerated: true,
              copiedFromWeek: Utils.formatDate(lastWeekStart)
            };
            Storage.saveRecord(newRecord);
          }
        }

        records = Storage.getRecords();
      }
    }

    const weekRecords = records.filter(r => {
      if (r.studentId !== user.id) return false;
      if (!r.taskType.startsWith('weekly')) return false;
      return weekDates.includes(r.date) || (r.date <= today && r.taskType.startsWith('weekly'));
    });

    return {
      required: weekRecords.filter(r => r.taskType === TaskManager.TaskType.WEEKLY_REQUIRED),
      optional: weekRecords.filter(r => r.taskType === TaskManager.TaskType.WEEKLY_OPTIONAL)
    };
  }

  static getRecord(recordId) {
    const records = Storage.getRecords();
    return records.find(r => r.id === recordId) || null;
  }

  static startTask(recordId) {
    const records = Storage.getRecords();
    const record = records.find(r => r.id === recordId);
    if (!record) return null;

    record.status = 'in_progress';
    record.startTime = Date.now();

    const index = records.findIndex(r => r.id === recordId);
    records[index] = record;
    Storage.saveRecords(records);

    return record;
  }

  static completeTask(recordId, data) {
    const records = Storage.getRecords();
    const record = records.find(r => r.id === recordId);
    if (!record) return null;

    record.status = 'completed';
    record.endTime = Date.now();
    record.actualDuration = data.actualDuration || 0;
    record.ratings = data.ratings || null;
    record.summary = data.summary || '';
    record.completedAt = Date.now();

    const index = records.findIndex(r => r.id === recordId);
    records[index] = record;
    Storage.saveRecords(records);

    this.checkDrops(record);
    this.checkWeeklyCompletion();

    return record;
  }

  static deleteTemplate(templateId) {
    Storage.deleteTemplate(templateId);
    return true;
  }

  static deleteRecord(recordId) {
    const records = Storage.getRecords();
    const filtered = records.filter(r => r.id !== recordId);
    Storage.saveRecords(filtered);
    return true;
  }

  static getTemplates() {
    return Storage.getTemplates() || [];
  }

  static getDailyStats(date = Utils.getToday()) {
    const tasks = this.getDailyTasks(date);
    const completedRequired = tasks.required.filter(t => t.status === 'completed').length;
    const completedOptional = tasks.optional.filter(t => t.status === 'completed').length;

    return {
      required: { total: tasks.required.length, completed: completedRequired },
      optional: { total: tasks.optional.length, completed: completedOptional },
      allRequiredCompleted: completedRequired === tasks.required.length && tasks.required.length > 0
    };
  }

  static getWeeklyStats() {
    const tasks = this.getWeeklyTasks();
    const weekDates = Utils.getWeekDates();

    const dailyRequiredTasks = tasks.required.filter(t => t.taskType === TaskManager.TaskType.DAILY_REQUIRED);
    const weeklyRequiredTasks = tasks.required.filter(t => t.taskType === TaskManager.TaskType.WEEKLY_REQUIRED);

    const dailyCompletion = {};
    weekDates.forEach(date => {
      const dayTasks = dailyRequiredTasks.filter(t => t.date === date);
      const completed = dayTasks.filter(t => t.status === 'completed').length;
      dailyCompletion[date] = {
        total: dayTasks.length,
        completed: completed,
        done: dayTasks.length > 0 && completed === dayTasks.length
      };
    });

    const completedDays = Object.values(dailyCompletion).filter(d => d.done).length;
    const totalDays = Object.values(dailyCompletion).filter(d => d.total > 0).length;

    const completedWeekly = weeklyRequiredTasks.filter(t => t.status === 'completed').length;

    const dailyOptionalTasks = tasks.optional.filter(t => t.taskType === TaskManager.TaskType.DAILY_OPTIONAL);
    const weeklyOptionalTasks = tasks.optional.filter(t => t.taskType === TaskManager.TaskType.WEEKLY_OPTIONAL);
    const completedOptionalDaily = dailyOptionalTasks.filter(t => t.status === 'completed').length;
    const completedOptionalWeekly = weeklyOptionalTasks.filter(t => t.status === 'completed').length;

    return {
      dailyCompletion,
      requiredDays: { completed: completedDays, total: totalDays },
      weeklyRequired: { total: weeklyRequiredTasks.length, completed: completedWeekly },
      weeklyOptional: { total: weeklyOptionalTasks.length, completed: completedOptionalWeekly },
      optional: {
        total: dailyOptionalTasks.length,
        completed: completedOptionalDaily
      }
    };
  }

  static checkDrops(record) {
    const today = Utils.getToday();

    if (record.taskType === TaskManager.TaskType.DAILY_REQUIRED) {
      Drop.triggerDailyRequiredItemDrop(record.id);

      const stats = this.getDailyStats(today);
      if (stats.allRequiredCompleted) {
        const alreadyDropped = Drop.hasDailyRequiredDropped(today);
        if (!alreadyDropped) {
          Drop.triggerAllDailyRequiredComplete();
        }
      }
    }

    if (record.taskType === TaskManager.TaskType.DAILY_OPTIONAL) {
      Drop.triggerDailyOptionalItemDrop();
    }
  }

  static checkWeeklyCompletion() {
    const stats = this.getWeeklyStats();
    if (stats.weeklyRequired.total > 0 &&
        stats.weeklyRequired.completed === stats.weeklyRequired.total) {
      const today = Utils.getToday();
      if (!this.hasWeeklyRequiredDropped(today)) {
        Drop.triggerWeeklyRequiredDrop();
        this.markWeeklyRequiredDropped(today);
      }
    }

    if (stats.weeklyOptional.total > 0 &&
        stats.weeklyOptional.completed === stats.weeklyOptional.total) {
      const today = Utils.getToday();
      if (!this.hasWeeklyOptionalDropped(today)) {
        Drop.triggerWeeklyOptionalDrop();
        this.markWeeklyOptionalDropped(today);
      }
    }

    if (stats.requiredDays.total > 0 && stats.requiredDays.completed < stats.requiredDays.total) {
      const today = Utils.getToday();
      if (!this.isDateExempted(today)) {
        this.markWeekIncomplete();
      }
    }
  }

  static markWeeklyRequiredDropped(date) {
    const user = Auth.getCurrentUser();
    if (!user) return;

    const settings = Storage.getSettings();
    const weekStart = Utils.formatDate(Utils.getWeekStart());
    if (!settings.weeklyRequiredDrops) settings.weeklyRequiredDrops = {};

    settings.weeklyRequiredDrops[user.id] = settings.weeklyRequiredDrops[user.id] || {};
    settings.weeklyRequiredDrops[user.id][weekStart] = true;
    Storage.saveSettings(settings);
  }

  static hasWeeklyRequiredDropped(date) {
    const user = Auth.getCurrentUser();
    if (!user) return false;

    const settings = Storage.getSettings();
    const weekStart = Utils.formatDate(Utils.getWeekStart());
    return settings.weeklyRequiredDrops?.[user.id]?.[weekStart] === true;
  }

  static markWeeklyOptionalDropped(date) {
    const user = Auth.getCurrentUser();
    if (!user) return;

    const settings = Storage.getSettings();
    const weekStart = Utils.formatDate(Utils.getWeekStart());
    if (!settings.weeklyOptionalDrops) settings.weeklyOptionalDrops = {};

    settings.weeklyOptionalDrops[user.id] = settings.weeklyOptionalDrops[user.id] || {};
    settings.weeklyOptionalDrops[user.id][weekStart] = true;
    Storage.saveSettings(settings);
  }

  static hasWeeklyOptionalDropped(date) {
    const user = Auth.getCurrentUser();
    if (!user) return false;

    const settings = Storage.getSettings();
    const weekStart = Utils.formatDate(Utils.getWeekStart());
    return settings.weeklyOptionalDrops?.[user.id]?.[weekStart] === true;
  }

  static markWeekIncomplete() {
    const settings = Storage.getSettings();
    const weekStart = Utils.formatDate(Utils.getWeekStart());
    settings.weekIncomplete = settings.weekIncomplete || {};
    settings.weekIncomplete[weekStart] = true;
    Storage.saveSettings(settings);
  }

  static isDateExempted(date) {
    const settings = Storage.getSettings();
    return settings.exemptDates?.includes(date) || false;
  }

  static shouldApplySundayPunishment() {
    const today = new Date();
    const dayOfWeek = today.getDay();
    if (dayOfWeek !== 0) return false;

    const weekStart = Utils.formatDate(Utils.getWeekStart());
    const settings = Storage.getSettings();

    if (settings.weekIncomplete?.[weekStart] === false) {
      return false;
    }

    const stats = this.getWeeklyStats();
    if (stats.requiredDays.total > 0 && stats.requiredDays.completed < stats.requiredDays.total) {
      return true;
    }

    return false;
  }

  static addExemptDate(date) {
    const settings = Storage.getSettings();
    if (!settings.exemptDates) {
      settings.exemptDates = [];
    }
    if (!settings.exemptDates.includes(date)) {
      settings.exemptDates.push(date);
      Storage.saveSettings(settings);
    }
    return true;
  }

  static getRemainingExemptCount() {
    const settings = Storage.getSettings();
    const exemptCount = settings.exemptCount || 3;
    const weekStart = Utils.formatDate(Utils.getWeekStart());
    const usedDates = settings.exemptDates || [];
    const weekUsed = usedDates.filter(d => {
      const dDate = new Date(d);
      const wStart = new Date(weekStart);
      const wEnd = new Date(wStart);
      wEnd.setDate(wStart.getDate() + 7);
      return dDate >= wStart && dDate < wEnd;
    }).length;
    return Math.max(0, exemptCount - weekUsed);
  }

  static requestExemption(date, reason = '') {
    const user = Auth.getCurrentUser();
    if (!user) return null;

    const request = {
      id: Utils.generateId(),
      studentId: user.id,
      studentUsername: user.username,
      date: date,
      reason: reason,
      status: 'pending',
      createdAt: Date.now(),
      updatedAt: null
    };

    Storage.saveExemptionRequest(request);
    return request;
  }

  static getExemptionRequests() {
    const user = Auth.getCurrentUser();
    if (!user) return [];

    const requests = Storage.getExemptionRequests();
    return requests
      .filter(r => r.studentId === user.id)
      .sort((a, b) => b.createdAt - a.createdAt);
  }

  static getParentExemptionRequests() {
    const requests = Storage.getExemptionRequests();
    return requests
      .filter(r => r.status === 'pending')
      .sort((a, b) => b.createdAt - a.createdAt);
  }

  static makeupTask(recordId) {
    const records = Storage.getRecords();
    const record = records.find(r => r.id === recordId);
    if (!record) return { success: false, error: '任务不存在' };

    const settings = Storage.getSettings();
    const makeupCount = settings.makeupCount || 3;
    const weekStart = Utils.getWeekStart();
    const weekDates = Utils.getWeekDates(weekStart);

    const makeupRecords = records.filter(r =>
      r.studentId === record.studentId &&
      r.isMakeup &&
      weekDates.includes(r.date)
    );

    if (makeupRecords.length >= makeupCount) {
      return { success: false, error: `本周补打卡次数已用完（${makeupCount}次）` };
    }

    const today = new Date();
    const taskDate = new Date(record.date);
    const daysDiff = Math.floor((today - taskDate) / 86400000);

    if (daysDiff > 7) {
      return { success: false, error: '只能补打卡7天内的任务' };
    }

    if (daysDiff < 0) {
      return { success: false, error: '不能补打卡未来日期的任务' };
    }

    record.status = 'completed';
    record.completedAt = Date.now();
    record.actualDuration = record.plannedDuration || 30;
    record.isMakeup = true;
    record.makeupDate = Utils.getToday();

    const index = records.findIndex(r => r.id === recordId);
    records[index] = record;
    Storage.saveRecords(records);

    return { success: true, record: record };
  }

  static getMakeupCount() {
    const user = Auth.getCurrentUser();
    if (!user) return { used: 0, total: 3 };

    const settings = Storage.getSettings();
    const makeupCount = settings.makeupCount || 3;
    const weekStart = Utils.getWeekStart();
    const weekDates = Utils.getWeekDates(weekStart);

    const records = Storage.getRecords();
    const makeupRecords = records.filter(r =>
      r.studentId === user.id &&
      r.isMakeup &&
      weekDates.includes(r.date)
    );

    return {
      used: makeupRecords.length,
      total: makeupCount,
      remaining: makeupCount - makeupRecords.length
    };
  }

  static applyWeeklyPunishment(studentId) {
    const userId = studentId || Auth.getCurrentUser()?.id;
    if (!userId) return false;

    const today = new Date();
    const yesterday = new Date(today);
    yesterday.setDate(today.getDate() - 1);

    const todayStr = Utils.formatDate(today);
    const yesterdayStr = Utils.formatDate(yesterday);

    Points.deleteRecordsInRange(yesterdayStr, todayStr, userId);

    const settings = Storage.getSettings();
    const weekStart = Utils.formatDate(Utils.getWeekStart());
    settings.weekIncomplete = settings.weekIncomplete || {};
    settings.weekIncomplete[weekStart] = false;
    Storage.saveSettings(settings);

    return true;
  }

  static detectAndApplySundayPunishment(studentId) {
    const stats = this.getWeeklyStats();
    const userId = studentId || Auth.getCurrentUser()?.id;
    if (!userId) return false;

    if (stats.requiredDays.total > 0 && stats.requiredDays.completed < stats.requiredDays.total) {
      const settings = Storage.getSettings();
      const weekStart = Utils.formatDate(Utils.getWeekStart());

      const exemptDates = settings.exemptDates || [];
      const weekDates = Utils.getWeekDates(new Date(weekStart));
      const exemptCount = exemptDates.filter(d => weekDates.includes(d)).length;

      if (exemptCount > 0) {
        return false;
      }

      this.applyWeeklyPunishment(userId);
      return true;
    }
    return false;
  }

  static getIncompleteRequiredTasks() {
    const user = Auth.getCurrentUser();
    if (!user) return [];

    const records = Storage.getRecords();
    const today = new Date();
    const weekStart = Utils.getWeekStart();
    const weekDates = Utils.getWeekDates(weekStart);

    return records.filter(r => {
      if (r.studentId !== user.id) return false;
      if (r.status === 'completed') return false;
      if (!r.taskType.includes('required')) return false;

      const taskDate = new Date(r.date);
      const daysDiff = Math.floor((today - taskDate) / 86400000);
      if (daysDiff > 7 || daysDiff < 0) return false;

      return true;
    });
  }

  static getTodayStudyTime() {
    const user = Auth.getCurrentUser();
    if (!user) return 0;

    const records = Storage.getRecords();
    const today = Utils.getToday();

    const todayRecords = records.filter(r =>
      r.studentId === user.id &&
      r.date === today &&
      r.status === 'completed' &&
      r.taskCategory === TaskManager.TaskCategory.STUDY
    );

    const totalSeconds = todayRecords.reduce((sum, r) => sum + (r.actualDuration || 0), 0);
    return (totalSeconds / 3600).toFixed(1);
  }

  static getTodaySportsTime() {
    const user = Auth.getCurrentUser();
    if (!user) return 0;

    const records = Storage.getRecords();
    const today = Utils.getToday();

    const todayRecords = records.filter(r =>
      r.studentId === user.id &&
      r.date === today &&
      r.status === 'completed' &&
      r.taskCategory === TaskManager.TaskCategory.SPORTS
    );

    const totalSeconds = todayRecords.reduce((sum, r) => sum + (r.actualDuration || 0), 0);
    return (totalSeconds / 3600).toFixed(1);
  }
}